
version: "3.9"

services:
    m4_entrega: 
      container_name: m4_entrega
      image: node:16
      build: .
      ports:
        - 3332:3333
      depends_on: 
        db:
          condition: service_healthy
       

    db:
      container_name: db_production
      image: postgres:14
      ports:
        - 5431:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=products_management
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d products_management"]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
       - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
       - db_production:/var/lib/postgresql/data
      
   
    dbtest:
      container_name: db_test
      image: postgres:14
      ports:
        - 5433:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=test_products
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d test_products"]
        interval: 10s
        timeout: 5s
        retries: 5
volumes:
  db_production:
    driver: local
   